# Site settings
title: WizK
email: kalkinblog1@gmail.com
author: WizK
description: "WizK Blog"
baseurl: ""
url: "http://www.wizk.tk/"
google_analytics:
animated: false


# Build settings

# Permalinks
permalink:	/:title

# Use kramdown as markdown parser engine.
markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

gems:
  - jekyll-sitemap

timezone: Asia/Seoul

paginate: 10
sass:
  compressed: true

