# Site settings
<<<<<<< HEAD
title:       WizK
email:       kalkinblog1@gmail.com
author:      WizK
description: "WizK Blog"
baseurl:     ""
url:         "http://wizk.tk"
=======
title:       Pixyll
email:       your_email@example.com
author:      John Otander
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://pixyll.com"
>>>>>>> de06d82da751c8fee9bb75cd8999d47418baa4c6

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
<<<<<<< HEAD
=======
medium_id:
>>>>>>> de06d82da751c8fee9bb75cd8999d47418baa4c6
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
<<<<<<< HEAD
share_facebook: true
share_twitter: true
share_googleplus: true
=======
share_facebook: false
share_twitter: false
share_googleplus: false
>>>>>>> de06d82da751c8fee9bb75cd8999d47418baa4c6
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
<<<<<<< HEAD
paginate:     7
=======
paginate:     4
>>>>>>> de06d82da751c8fee9bb75cd8999d47418baa4c6
sass:
  compressed: true
gems:
  - jekyll-sitemap
